config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :calendars, only: [:index] do
  resources :events
  # end
  get "/weekly", to: "events#weekly"
  get "/monthly", to: "events#monthly"
  get "/daily", to: "events#daily"

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  validates :time_difference, presence: true

  # validate :cannot_have_conflict
  validates :start_time, :end_time, :overlap => {:scope => ["user_id", "end_date"]}
  before_save :geocode_endpoints
  
  # def cannot_have_conflict
  #   conflicts = Event.where(user: user).where("\
  #     (start_time < :start_time AND end_time > :start_time)\
  #     OR (start_time < :end_time AND end_time > :end_time)",
  #     start_time: start_time, end_time: end_time)
  #   if conflicts.present?
  #     errors.add(:start_time, "Not possible Fool, check the time lol")
  #   end
  # end

  def start_date_time
    return nil unless start_date && start_time
    DateTime.new(start_date.year, start_date.month, start_date.day, start_time.hour, start_time.min, start_time.sec, start_time.zone)
  end

  def travel_time_class
     if category == "Workout"
      "blue-travel"
     elsif category == "Work"
      "red-travel"
     elsif category == "Social"
      "yellow-travel"
     elsif category == "Reminder"
      "green-travel"
     elsif category == "Birthday"
      "orange-travel"
     end
  end
  
  def event_time_class
    if category == "Workout"
      "blue-event"
    elsif category == "Work"
      "red-event"
    elsif category == "Social"
      "yellow-event"
    elsif category == "Reminder"
      "green-event"
    elsif category == "Birthday"
      "orange-event"
    end
  end

  # def day_as_string
  #    if date.wday == 0
  #     "Sunday"
  #    elsif date.wday == 1
  #     "Monday"
  #    elsif date.wday == 2
  #     "Tuesday"
  #    elsif date.wday == 3
  #     "Wednesday"
  #    elsif date.wday == 4
  #     "Thursday"
  #    elsif date.wday == 5
  #     "Friday"
  #    elsif date.wday == 6
  #     "Saturday"
  #    end
  # end

  private

  def geocode_endpoints
    if previous_location_changed?
      geocoded = Geocoder.search(previous_location).first
      if geocoded
        self.start_lat = geocoded.latitude
        self.start_lng = geocoded.longitude
      end
    end

    if event_location_changed?
      geocoded = Geocoder.search(event_location).first
      if geocoded
        self.end_lat = geocoded.latitude
        self.end_lng = geocoded.longitude
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events

  after_create :send_welcome_email

  private

  def send_welcome_email
    UserMailer.with(user: self).welcome.deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  def default_url_options
  { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || daily_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def weekly
  end

  def monthly
  end

  def daily
    @day = params[:start_date] || Date.today
    @events = []
    @events = Event.where(user_id: current_user.id, end_date: @day)
    @events = [] if @events.nil?
  end

  def show
    @markers = [
      {
        lat: @event.start_lat,
        lng: @event.start_lng
      }, 
      {
        lat: @event.end_lat,
        lng: @event.end_lng
      }
    ]
  end

  def new
    @date = params[:date]
    @event = Event.new
  end

  # def secondnew
  #   @date = params[:date]
  #   @event = Event.new
  # end

  def create
    @event = Event.new(events_params)
    @event.user = current_user
    if @event.end_date.nil?
      @event.end_date = @event.start_date
    end
    @event.start_date = @event.end_date if @event.start_date.nil?
    if @event.save
      EventJob.set(wait_until: @event.start_date_time.ago(@event.time_difference/1000)).perform_later(@event.id)
      redirect_to "/daily/?start_date=#{@event.end_date}"
    else
      render 'new'
    end
  end

  def edit
    @date = @event.end_date
  end

  def update
    if @event.update(events_params)
      redirect_to "/daily/?start_date=#{params[:event][:end_date]}"
    else
      render 'edit'
    end
  end

  def destroy
    @event.destroy
    redirect_to daily_path
  end

  private

  def events_params
    params.require(:event).permit(:previous_location, :event_location, :description, :name,
      :category, :start_time, :end_time, :start_date, :end_date, :travel_type, :time_difference)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
  end
end

app/views/events/_form.html.erb
<%= simple_form_for @event do |f| %>
  <div class="container event_form" style="margin-bottom: 100px;">
    <%= f.input :end_date, as: :hidden, input_html: { value: @date } %>
    <%= f.input :name %>
    <%= f.input :category, :collection => ["Work", "Social", "Reminder", "Workout"]%>


    <div class="form-input-times" style="display: flex; justify-content: space-around; text-align: center">
      <% if @date == "" || @date.nil? %>

        <div class="d-flex flex-row justify-content-between align-items-center">
          <%= f.input :start_date, default: {day: @date}, order: [:day, :month, :year] %>
        </div>
      <% end %>
    </div>


    <div class="form-input-times" style="display: flex; justify-content: space-around; margin-top: 8px; text-align: center">
      <%= f.input :start_time %>
      <%= f.input :end_time %>
    </div>

    <%= f.input :previous_location %>
    <%= f.input :event_location %>

    <div style="display: flex; justify-content: center; text-align: center">
      <%= f.input :travel_type, :collection => ["Car", "Pedestrian"] %>
      <%= f.input :time_difference, as: :hidden, input_html: { id: "time_difference", hidden: true } %>
    </div>

    <div style="display: flex; justify-content: space-around; margin-top: 12px;">
      <button style="margin-top: 4px; margin-right: 12px; background-color: #01A6B0; border: none; border-radius: 12px; height: 30px; width: 130px; box-shadow: 1px 1px 1px rgba(0, 0, 0, 0.1); color: white;" type="button" id="cal_time" >Calculate time</button>
      <p style="z-index: 5; right: -25px; top: -27px; padding: 8px; border: 1px solid #ced4da; border-radius: 2px; width: 150px; text-align: center; " id="time_difference_display">Time</p>
    </div>

    <div style="margin-top: 3%">
      <%= f.input :description, class: "mt-1" %>
    </div>
  </div>

  <div class="footer">
    <div class="footer-buttons">
      <%= link_to "Back", :back, class:"btn back_button", style:"text-align: center;"%>
      <%= f.button :submit, class:"btn new_event_button" %>
    </div>
  </div>
<% end %>

app/views/events/daily.html.erb
<div class="header">
  <div class="drop-down">
    <%= link_to "Monthly View", monthly_path, class: "btn daily-view-button" %>
    <%# <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Change View
    </button>
    <div class="dropdown-menu dropdown-menu-right" style="width: " aria-labelledby="dropdownMenuButton">
      <a class="dropdown-item" href=<%= monthly_path %>
      <%# <a class="dropdown-item" href=<%= weekly_path %>
    </div>
  </div>
</div>

<div id="daily-card" style="margin-bottom: 44px;">
  <%= calendar number_of_days: 1 do |date| %>
    <div class="times">
      <% array = ["00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00", "24:00"] %>
      <div class="times-display">
        <% array.each do |time| %>
          <div class="d-flex align-items-center justify-content-between">

            <p class="daily-time"><%= time %></p>
            <div class="line"></div>
        
          </div>
        <% end %>
      </div>

      <div class="background-color-times"></div>

      <div class="events-container">
        <% @events.each do |event| %>
          <% time_event = ((event.end_time - event.start_time) / 60) / 60 %>
          <% beginning_of_day_difference = ((event.start_time - event.start_time.beginning_of_day) / 60) / 60 %>
          <% time_travel = (event.time_difference / (1000 * 60 * 60)) %>
          <% time_travel_percentage = (time_travel / 24) * 100 %>
          <% minus_travel = event.time_difference %>

          <%= link_to event_path(event) do %>
            <div class="travel_time <%= event.travel_time_class %>" style="height: <%= time_travel_percentage %>%; top: <%= ((beginning_of_day_difference / 24) * 100) - time_travel_percentage %>%; width: 200px;">
              <% unless time_travel_percentage < 0.6 %>
                <p style="color: black;"><i class="far fa-clock"></i> <%= (time_travel * 60).round %> Minutes Travel Time</p>
              <% end %>
            </div>

            <div class="event <%= event.event_time_class %> %" style="overflow: hidden; padding: 8px; height: <%= ((time_event / 24) * 100) %>%; top: <%= ((beginning_of_day_difference / 24) * 100) %>%;">
              <% unless ((time_event / 24) * 100) < 0.7 %>
                <h4 class="title_daily"><%= event.name %> </h4>
              <% end %>
              <% unless ((time_event / 24) * 100) < 5 %>
                <p style="color: black; font-size: 16px;"><i class="fas fa-thumbtack"></i> <%= event.event_location %></p>
              <% end %>
              <% unless ((time_event / 24) * 100) < 7 %>
                <p style="color: black;"><i class="fas fa-tags"></i> <%= event.category %></p>
              <% end %>
              <% unless ((time_event / 24) * 100) < 12 %>
                <% if event.description == "" %>
                  <p style="color: black;"><%= event.description %></p>
                <% else %>
                  <p style="color: black;"><i class="far fa-clipboard"></i> <%= event.description %></p>
                <% end %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>

  <i class="next_button fas fa-arrow-circle-right"></i>
  <i class="previous_button fas fa-arrow-circle-right"></i>

</div>

<div class="footer">
  <div class="footer-buttons">
    <%= link_to "Back", monthly_path, class:"btn back_button", style:"text-align: center;"%>
    <%= link_to "Add Event", new_event_path(date: @day), class:"btn create_event_button"%>
  </div>
</div>

app/views/events/edit.html.erb
<%= render "form" %>

app/views/events/monthly.html.erb
<%= month_calendar do |date| %>
    <%= link_to '', "data-toggle": "modal", "data-target": "#exampleModal-#{date}"  do %>
      <p class="days-integer" style=“color: black;“><%= date.day %></p>
      <%# <% Event.where(user_id: current_user.id, end_date: date).each do |event| %>
        <%# <%= event.name %>
      <%# <% end %>
    <% end %>
     <div class="modal fade" id="exampleModal-<%= date %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
       <div class="modal-dialog modal-dialog-centered" role="document">
         <div class="modal-content">
           <div class="modal-header">
              <div>
                <p class="day-monthly">
                  <% if date.wday == 0 %>
                    <%= "Sunday" %>
                  <% elsif date.wday == 1 %>
                    <%= "Monday" %>
                  <% elsif date.wday == 2 %>
                    <%= "Tuesday" %>
                  <% elsif date.wday == 3 %>
                    <%= "Wednesday" %>
                  <% elsif date.wday == 4 %>
                    <%= "Thursday" %>
                  <% elsif date.wday == 5 %>
                    <%= "Friday" %>
                  <% elsif date.wday == 6 %>
                    <%= "Saturday" %>
                  <% end %>
                </p>
                <p class="month-monthly">
                  <% if date.month == 0 %>
                    <%= "December" %>
                  <% elsif date.month == 1 %>
                    <%= "January" %>
                  <% elsif date.month == 2 %>
                    <%= "February" %>
                  <% elsif date.month == 3 %>
                    <%= "March" %>
                  <% elsif date.month == 4 %>
                    <%= "April" %>
                  <% elsif date.month == 5 %>
                    <%= "May" %>
                  <% elsif date.month == 6 %>
                    <%= "June" %>
                  <% elsif date.month == 7 %>
                    <%= "July" %>
                  <% elsif date.month == 8 %>
                    <%= "August" %>
                  <% elsif date.month == 9 %>
                    <%= "September" %>
                  <% elsif date.month == 10 %>
                    <%= "October" %>
                  <% elsif date.month == 11 %>
                    <%= "November" %>
                  <% end %>
                </p>
              </div>
              <h6 class="modal-title btn" id="exampleModalLongTitle">&nbsp<%= date %></h6>

              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <% if Event.where(start_date: date, user: current_user).empty? %>
              <p class="no-event-listed" >No events listed</p>
            <% else %>
              <% Event.where(start_date: date, user: current_user).each do |event| %>
                <%= link_to event_path(event), class: "links" do %>
                  <div class="modal-body">
                    <p style="font-weight: bold;"><%= event.name %></p>
                    <br>
                    <i class="fas fa-thumbtack"></i> <%= event.event_location %>
                    <br>
                    <i class="far fa-clock"></i> <%= event.start_time.strftime("%I:%M %P") %>
                  </div>
                <% end %>
              <% end %>
            <% end %>

            <div class="modal-footer">
              <%= link_to "Daily View", daily_path(start_date: date), class: "btn daily-view-button add-btn"  %>
              <!-- <a class="btn btn-secondary add-btn" href="/events/new">Add Event</a> -->
              <%= link_to "Add Event", new_event_path(date: date), class:"btn btn-secondary add-btn"%>

           </div>

         </div>
       </div>
     </div>
  <% end %>

<i class="next_button fas fa-arrow-circle-right"></i>
<i class="previous_button fas fa-arrow-circle-right"></i>

<div class="footer">
  <div class="footer-buttons">
    <%= link_to "Back", daily_path, class:"btn btn-danger back_button", style:"text-align: center;"%>
    <%= link_to "Add Event", new_event_path(date: @day), class:"btn create_event_button"%>
  </div>
</div>

app/views/events/new.html.erb
<%= render "form", date: params[:date] %>

app/views/events/show.html.erb
<div id="weather">
</div>

<div>
  <div class="show-card" style="z-index: 10; position; relative;">
    <button type="button" class="collapsible"></button>
    <h4 style="position: relative; margin-bottom: 2px;"><%= @event.name %>
    <%= link_to event_path(@event), method: :delete, data: { confirm: "Are you sure you would like to DELETE " + @event.name }, class:"icon", style:"margin-left: 8px;" do %>
      <i class="fas fa-trash trash-icon"></i>
    <% end %></h4>
    
    <p style="margin-bottom: 12px; margin-top: 6px; font-size: 20px;"><%= @event.start_date %></p>
    
    <div style="display: flex; justify-content: center !important;">
      <i style="margin-top: 2px;" class="fas fa-thumbtack"></i>
      <p style="margin-bottom: 12px; margin-left: 4px;" id="location"><%= @event.event_location %></p>
    </div>
    <p style="margin-bottom: 12px;"><i class="far fa-clock"></i> <%= @event.start_time.strftime("%I:%M %P") %> - <%= @event.end_time.strftime("%I:%M %P") %></p>
    <% if @event.description != "" %>
      <p style="font-size: 12px; margin: 0 15%;"><i class="far fa-clipboard"></i> <%= @event.description %></p>
    <% end %>
  </div>

  <div id="map"
    style="width: 100vw; height: 90%; position: absolute; top: 70px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

<div class="footer">
  <div class="footer-buttons">
    <%= link_to "Back", daily_path(params[:start_date]), class:"btn back_button", style:"text-align: center;"%>
    <%= link_to "Edit Event", edit_event_path(@event), class: "btn edit_event_button" %>
  </div>
</div>

app/views/events/weekly.html.erb
<div class="header">
  <h1>WEEKLY VIEW</h1>

  <div class="drop-down">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Change View
  </button>
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href=<%= daily_path %>>Daily</a>
    <a class="dropdown-item" href=<%= monthly_path %>>Monthly</a>
  </div>
  </div>
</div>

<div style="display: flex; justify-content: space-around;">
  <%= week_calendar number_of_weeks: 1 do |date| %>
    <%= link_to root_path(start_date: date) do %>
      <p style="color: black;"><%= date.day %></p>
    <% end %>
  <% end %>
</div>

<div class="footer">
  <%= link_to "Back", :back, class:"btn btn-danger back_button", style:"text-align: center;"%>
  <%= link_to "Add Event", new_event_path(date: @day), class:"btn create_event_button"%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smart Calendar: Organise Your Life</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('smart_cal.png') %>

    <link href="https://fonts.googleapis.com/css2?family=Karla:wght@400;700&family=Roboto:wght@300;400;500;700&family=Titillium+Web:wght@300;400;600;700&display=swap" rel="stylesheet">
    <link href='https://api.mapbox.com/mapbox-gl-js/v1.11.1/mapbox-gl.css' rel='stylesheet' />

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<!-- <h1>Pages#home</h1> -->

<!-- <button class="button"><span>SIGN-UP </span></button> -->
<div class="container d-flex flex-column justify-content-center align-items-center mt-5 main">

    <!-- <h1>SmartCal</h1> -->
  <div class="main-heading text-center mb-5" style="width: 70%; font-size: 20px;"><h1><strong>Smart Calendar</strong></h1></div>
  <p class="join-text" >Join today!</p>
  <div class="login-buttons" >
    <div class="button-width"><%= link_to "SIGN-IN", new_user_session_path ,class: "btn  btn-sm btn-block buttons mt-3 mb-3 login-button"%></div>
    <div class="button-width"><%= link_to "SIGN-UP", new_registration_path(:user),class: "btn btn-sm btn-block buttons mb-5 signup-button" %></div>
  </div>
  <div class="text-home d-flex justify-content-center">Find your place, <br> Find your time!</div>
</div>
<!-- <button class="button"><span>SIGN-IN</span></button> -->
<!-- <p>Find me in app/views/pages/home.html.erb</p> -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="display: flex; justify-content: space-between;">
  <div>
    <%= link_to daily_path, class: "navbar-brand" do %>
      <%= image_tag "smart_calendar.png", style:"width: 100px;" %>
    <% end %>
  </div>

  <div>
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="sign-out-icon fas fa-sign-out-alt"></i>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar daily-simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view, class:"previous"%>
    <%= link_to t('simple_calendar.next', default: 'Previous'), calendar.url_for_next_view, class:"next" %>
  </div>

  <table class="table daily_table table-striped">
    <thead class="table_daily_head">
      <tr class="daily_days">
        <% date_range.slice(0, 7).each do |day| %>
        <% th = [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 24, 25, 26, 27, 28, 29, 30] %>
          <th style="position: absolute; left: 68px; font-size: 14px; top: 73px;" class="daily_day"><% if day.day == 1 || day.day == 21 || day.day == 31 %>
            <%= day.day %>st
          <% elsif th.include?(day.day) %>
            <%= day.day %>th
          <% elsif day.day == 2 || day.day == 22 %>
            <%= day.day %>nd
          <% elsif day.day == 3 || day.day == 23 %>
            <%= day.day %>rd
          <% end %>
          
          
          </th>
          <th class="daily_day"><%= t('date.abbr_day_names')[day.wday] %></th>
          <th class="daily_day" style="font-size: 11px; top: 104px;"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="header-monthly">
  <div class="date-monthly-page">
    <h1 class="month-monthly-page"><%= t('date.month_names')[start_date.month].capitalize %></h1>
    <p class="year-monthly-page"><%= start_date.year %></p>
  </div>

  <div class="drop-down-month">
    <%= link_to "Daily View", daily_path, class: "btn daily-view-button" %>
    <%# <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Monthly View
    </button>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
      <a class="dropdown-item" href=<%= daily_path %>
      <%# <a class="dropdown-item" href=<%= weekly_path %>
  </div>
</div>

<div style="display: flex; justify-content: space-around;">
  <div class="simple-calendar">
    <div class="calendar-heading">
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </div>

    <table class="table table-striped monthly-table">
      <thead>
        <tr>
          <% date_range.slice(0, 7).each do |day| %>
            <th class="table-header"><%= t('date.abbr_day_names')[day.wday] %></th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% date_range.each_slice(7) do |week| %>
          <tr class="month-tr">
            <% week.each do |day| %>
              <%= content_tag :td, class: calendar.td_classes_for(day) do %>
                <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                  <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
                <% else %>
                  <% passed_block.call day, sorted_events.fetch(day, []) %>
                <% end %>
              <% end %>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <div style="width: 300px; overflow: scroll;">
    <table class="table table-striped">
      <thead>
        <tr>
          <% date_range.slice(0, 7).each do |day| %>
            <th><%= t('date.abbr_day_names')[day.wday] %></th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% date_range.each_slice(7) do |week| %>
          <tr>
            <% week.each do |day| %>
              <%= content_tag :td, class: calendar.td_classes_for(day) do %>
                <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                  <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
                <% else %>
                  <% passed_block.call day, sorted_events.fetch(day, []) %>
                <% end %>
              <% end %>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>